Update files_download_and_release.yml

diff --git a/.github/workflows/files_download_and_release.yml b/.github/workflows/files_download_and_release.yml
--- a/.github/workflows/files_download_and_release.yml
+++ b/.github/workflows/files_download_and_release.yml
@@ -49,6 +49,16 @@ jobs:
 
           curl -sL "${glibc_2_38_url}" > glibc.2.38.tar.xz
 
+      - name: glibc 2.39
+        run: |
+          glibc_2_39_url="https://ftp.gnu.org/gnu/libc/glibc-2.39.tar.xz"
+          echo "glibc_2_39=2.39" >> $GITHUB_ENV
+
+          printf "%s\n" "| glibc_2_39 | 2.39 | ${glibc_2_39_url} |" >> body.md
+          printf "239" >> tag_name.txt
+
+          curl -sL "${glibc_2_39_url}" > glibc.2.39.tar.xz
+
       - name: zlib-ng
         run: |
           zlib_url="https://github.com/zlib-ng/zlib-ng.git"
@@ -112,6 +122,13 @@ jobs:
             boost_url="https://boostorg.jfrog.io/artifactory/main/release/${boost_version}/source/boost_${boost_version//./_}.tar.gz"
           elif curl -sfLI "https://archives.boost.io/release/${boost_version}/source/boost_${boost_version//./_}.tar.gz" &> /dev/null; then
             boost_url="https://archives.boost.io/release/${boost_version}/source/boost_${boost_version//./_}.tar.gz"
+          elif curl -sfLI "https://sourceforge.net/projects/boost/files/boost/${boost_version}/boost_${boost_version//./_}.tar.gz" &> /dev/null; then
+            boost_url="https://sourceforge.net/projects/boost/files/boost/${boost_version}/boost_${boost_version//./_}.tar.gz"
+          elif curl -sfLI "https://github.com/userdocs/boost/releases/download/boost-${boost_version}/boost_${boost_version//./_}.tar.gz" &> /dev/null; then
+            boost_url="https://github.com/userdocs/boost/releases/download/boost-${boost_version}/boost_${boost_version//./_}.tar.gz"
+          else
+            printf '%s\n' "Error: Unable to find a download link for Boost version: $boost_version"
+            exit 1
           fi
 
           echo "boost=${boost_version}" >> $GITHUB_ENV
